"""Add book_rankings table and new columns to user_books

Revision ID: 1810f2fb5317
Revises: e67312ef69c5
Create Date: 2025-01-04 06:35:44.139666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1810f2fb5317'
down_revision = 'e67312ef69c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('list_name', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('bestsellers_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('current_page', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.drop_column('current_page')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    op.drop_table('book_rankings')
    # ### end Alembic commands ###
