"""Add categories, retail_price, and currency_code to books

Revision ID: d13301d4dad2
Revises: d3cf17632c45
Create Date: 2025-01-19 15:24:45.283314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13301d4dad2'
down_revision = 'd3cf17632c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('retail_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('currency_code', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('currency_code')
        batch_op.drop_column('retail_price')
        batch_op.drop_column('categories')

    # ### end Alembic commands ###
